FROM codesignal/ubuntu-base:v9.2.0

# Node and npm are already inherited from ubuntu-base.
RUN npm install -g --unsafe-perm=true \
    async \
    axios \
    chai \
    chai-http \
    co \
    connect \
    crypto-js \
    debug \
    express \
    forever \
    futil \
    http \
    ip-router \
    ip-to-int \
    ipaddr.js \
    jquery \
    lodash \
    mocha \
    mongodb \
    mongoose \
    mysql \
    mysql2 \
    node-fetch \
    rambda \
    request \
    rxjs \
    sequelize \
    shelljs \
    sys \
    underscore \
    validator  \
    when \
    ws
