FROM codesignal/ubuntu-base:v1.1

# Node and npm inherited from ubuntu-base.
RUN npm install -g \
    async \
    co \
    connect \
    crypto-js \
    debug \
    forever  \
    http \
    jquery \
    lodash \
    mysql \
    mysql2 \
    request \
    sequelize \
    shelljs \
    sys \
    underscore \
    validator  \
    when \
    ws 

ENV NODE_PATH=/usr/lib/node_modules/
