FROM codesignal/ubuntu-base:v6.0

# Node and npm inherited from ubuntu-base.
RUN npm install -g --unsafe-perm=true \
    async \
    axios \
    chai \
    co \
    connect \
    crypto-js \
    debug \
    forever \
    futil \
    http \
    jquery \
    lodash \
    mocha \
    mongodb \
    mysql \
    mysql2 \
    node-fetch \
    rambda \
    request \
    rxjs \
    sequelize \
    shelljs \
    sys \
    underscore \
    validator  \
    when \
    ws

ENV NODE_PATH=$NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules
