FROM codesignal/ubuntu-base:v7.1

#Install TypeScript and testing libraries
RUN npm install -g \
    chai \
    mocha \
    ts-node \
    typescript \
    @types/chai \
    @types/node \
    @types/mocha
