FROM codesignal/js:v8.1.0

# Install TypeScript and testing libraries
RUN npm install -g \
    source-map-support \
    ts-node \
    typescript \
    @types/chai \ 
    @types/express \
    @types/node \
    @types/mocha
